### PR TITLE
updated kylin.sh changes

### PR DESCRIPTION
**Pull request by vipinkumar7**
with this initial pool  space configuration more joins are running faster and not as earlier i was getting out of error with complex queries

### CODE REVIEW

**Comment by binmahone** [comment]
hi @vipinkumar7 

kylin.sh is moved to Kylin/bin, can you please pull the lastest code and make the pull request again?

**Comment by vipinkumar7** [comment]
Some guys are using this branch 0.6.5 also which is working on production so can we have this commit here also

**Comment by lukehan** [comment]
Hi @vipinkumar7, could you please pull request to 0.6 branch instead of master one? the current master branch already migrated to v0.7.x which is different than 0.6.x.

Thanks.

**Comment by vipinkumar7** [comment]
I hava done changes to current master and tested it its working fine I did sync of my fork  with 0.6 version.

**Pull request closed without merging**
