### PR TITLE
REST API get cube desc NullPointerException when cube is not exists

### PR DESCRIPTION
**Pull request by romansew**
REST API get cube desc NullPointerException when cube is not exists

### CODE REVIEW

**Comment by lukehan** [comment]
JIRA: https://issues.apache.org/jira/browse/KYLIN-657

**Comment by lukehan** [comment]
Could you please pull request to "Staging" branch?

Thanks.

Luke

**Comment by romansew** [comment]
OK

**Comment by liyang-gmt8** [comment]
Pls pull request to staging branch at https://github.com/apache/incubator-kylin/ next time. That's the official git. :-)

**Comment by romansew** [comment]
Ok, Thanks.

**Pull request merged**
